In [1]:
import pandas as pd

import numpy as np

In [3]:
from sklearn import preprocessing
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline, FeatureUnion

# for cross validation
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
#from sklearn.model_selection import cross_validation
from sklearn.model_selection import cross_val_predict, cross_val_score

# for various metrics and reporting
from sklearn import metrics 
from sklearn.metrics import roc_curve
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# feature selection
from sklearn.feature_selection import SelectFromModel

# xgboost library
from xgboost import XGBClassifier

# plot feature importance
from xgboost import plot_importance, plot_tree

In [2]:
import matplotlib.pyplot as plt
plt.rc("font", size=14)

# we will use the seaborn for visually appealing plots
import seaborn as sns
sns.set() # set the seaborn stylesheet
#sns.set(style="white")
#sns.set(style="whitegrid")

In [18]:
import sys
import types
import pandas as pd
from botocore.client import Config
import boto3

def __iter__(self): return 0

# boto3.client
# # @hidden_cell
# # The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# # You might want to remove those credentials before you share your notebook.
# response = boto3.client(service_name='s3',
#     aws_access_key_id='U2v61-Sy7j8htddu5cFZJe9EEgUeCqILurs3Vj9nn-4B',
#     aws_secret_access_key="https://iam.ng.bluemix.net/oidc/token",
#     config=Config(signature_version='oauth'),
#     endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

# #body = client_9ebc573937b647fdaea67b50c5ffa1e9.get_object(Bucket='pythondatasciencenotebooks238af3dbc1384aaebbcd5465d478db62',Key='bank.csv')['Body']
# body = client_9ebc573937b647fdaea67b50c5ffa1e9.get_object(Bucket='pythondatasciencenotebooks238af3dbc1384aaebbcd5465d478db62',Key='bank.csv')['Body']
# # add missing __iter__ method, so pandas accepts body as file-like object
# if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

# #df_data_1 = pd.read_csv(body)
# #df_data_1.head()

# data_raw_all = pd.read_csv(body, header=0, sep=";")

# data_raw_all.head()

In [21]:
data_raw_all = pd.read_csv("C:\Users\hedi\Downloads\credentials(4).csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-21-74e11925b760>, line 1)

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
import operator


In [23]:
vocabulary = set()

for doc in df_news.Clean_Keyword:
    vocabulary.update(doc.split(','))

vocabulary = list(vocabulary)

NameError: name 'df_news' is not defined

In [24]:


text="As the new coronavirus continues to spread around the world, some medical experts say it could become as widespread as the common flu. But as the number of casualties rise, thousands have also recovered.Few want to talk about their experience publicly, because of the discrimination and stigma they could face. However, one woman in Singapore, where there have been more than 100 cases, decided it was time to speak out.Here’s Julie's story.Reporting by Karishma Vaswani and Christine Hah.Filmed and edited by Jone Chang and Muhammad Fahmi Bin Jamal."

words=text.split(" ")

In [25]:
print(words)

['As', 'the', 'new', 'coronavirus', 'continues', 'to', 'spread', 'around', 'the', 'world,', 'some', 'medical', 'experts', 'say', 'it', 'could', 'become', 'as', 'widespread', 'as', 'the', 'common', 'flu.', 'But', 'as', 'the', 'number', 'of', 'casualties', 'rise,', 'thousands', 'have', 'also', 'recovered.Few', 'want', 'to', 'talk', 'about', 'their', 'experience', 'publicly,', 'because', 'of', 'the', 'discrimination', 'and', 'stigma', 'they', 'could', 'face.', 'However,', 'one', 'woman', 'in', 'Singapore,', 'where', 'there', 'have', 'been', 'more', 'than', '100', 'cases,', 'decided', 'it', 'was', 'time', 'to', 'speak', 'out.Here’s', "Julie's", 'story.Reporting', 'by', 'Karishma', 'Vaswani', 'and', 'Christine', 'Hah.Filmed', 'and', 'edited', 'by', 'Jone', 'Chang', 'and', 'Muhammad', 'Fahmi', 'Bin', 'Jamal.']


In [27]:
wordset=set(words)

In [30]:
x=dict.fromkeys(wordset,0)

In [31]:
type(x)

dict

In [32]:
for word in words :
    x[word]+=1

In [33]:
x

{'medical': 1,
 'new': 1,
 'experts': 1,
 'recovered.Few': 1,
 'coronavirus': 1,
 'some': 1,
 'Bin': 1,
 'However,': 1,
 'flu.': 1,
 'could': 2,
 'casualties': 1,
 'there': 1,
 'widespread': 1,
 'Vaswani': 1,
 'Chang': 1,
 'speak': 1,
 'as': 3,
 'also': 1,
 'it': 2,
 'spread': 1,
 'to': 3,
 'want': 1,
 'world,': 1,
 'in': 1,
 'cases,': 1,
 'time': 1,
 'Christine': 1,
 'rise,': 1,
 'where': 1,
 'Hah.Filmed': 1,
 'common': 1,
 'they': 1,
 'than': 1,
 'continues': 1,
 'number': 1,
 '100': 1,
 'the': 5,
 'thousands': 1,
 'talk': 1,
 'more': 1,
 'But': 1,
 'As': 1,
 'out.Here’s': 1,
 'woman': 1,
 'Karishma': 1,
 'become': 1,
 'publicly,': 1,
 'because': 1,
 'was': 1,
 'have': 2,
 'Fahmi': 1,
 'and': 4,
 'been': 1,
 "Julie's": 1,
 'edited': 1,
 'decided': 1,
 'their': 1,
 'discrimination': 1,
 'one': 1,
 'face.': 1,
 'story.Reporting': 1,
 'Jone': 1,
 'experience': 1,
 'Muhammad': 1,
 'around': 1,
 'about': 1,
 'of': 2,
 'stigma': 1,
 'Jamal.': 1,
 'Singapore,': 1,
 'say': 1,
 'by': 2}

In [39]:
import pandas as pd
pd.DataFrame(x,0)

TypeError: Index(...) must be called with a collection of some kind, 0 was passed

In [41]:

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer


In [42]:
df=pd.read_csv('SMSSpamCollection',sep='\t',names=['Status','Message'])

In [43]:
df


Status                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [44]:
df.loc[df["Status"]=='ham',"Status",]=1
df.loc[df["Status"]=='spam',"Status",]=0

In [45]:
df


Status                                            Message
0         1  Go until jurong point, crazy.. Available only ...
1         1                      Ok lar... Joking wif u oni...
2         0  Free entry in 2 a wkly comp to win FA Cup fina...
3         1  U dun say so early hor... U c already then say...
4         1  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      0  This is the 2nd time we have tried 2 contact u...
5568      1               Will ü b going to esplanade fr home?
5569      1  Pity, * was in mood for that. So...any other s...
5570      1  The guy did some bitching but I acted like i'd...
5571      1                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [46]:

df_x=df["Message"]
df_y=df["Status"]

In [47]:
cv = TfidfVectorizer(min_df=1,stop_words='english')

In [55]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)


In [56]:
x_traincv = cv.fit_transform(["Hi How are you How are you doing","Hi what's up","Wow that's awesome"])


In [57]:
x_traincv.toarray()

array([[0.        , 0.79596054, 0.60534851, 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        , 0.70710678]])

In [58]:

cv.get_feature_names()

['awesome', 'doing', 'hi', 'wow']

In [59]:
cv1 = TfidfVectorizer(min_df=1,stop_words='english')


In [60]:
x_traincv=cv1.fit_transform(x_train)

In [62]:
x_traincv.toarray()


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.19618715, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [63]:
x_testcv=cv1.transform(x_test)

In [70]:
a=x_testcv.toarray()


In [68]:
mnb = MultinomialNB()
y_train=y_train.astype('int')


In [71]:
cv1.inverse_transform(a[0])

[array(['amp', 'beneath', 'come', 'dreams', 'goodnite', 'light', 'moon',
        'pale', 'sweet', 'think', 'true'], dtype='<U27')]

In [73]:
x_train.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

In [77]:

x_testcv=cv1.transform(x_test)
b=x_testcv.toarray()

In [80]:
cv1.inverse_transform(b[0])


[array(['amp', 'beneath', 'come', 'dreams', 'goodnite', 'light', 'moon',
        'pale', 'sweet', 'think', 'true'], dtype='<U27')]

In [81]:
mnb = MultinomialNB() 

In [82]:
y_train=y_train.astype('int')


In [83]:
y_train


1457    1
472     1
2481    0
243     1
1413    1
       ..
3671    1
709     0
2487    1
174     1
1146    0
Name: Status, Length: 4457, dtype: int32

In [94]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [95]:
testmessage=x_test.iloc[0]

In [86]:

testmessage

'somewhere out there beneath the pale moon light someone think in of u some where out there where dreams come true... goodnite &amp; sweet dreams'

In [96]:
predictions=mnb.predict(x_testcv[0])

In [97]:
predictions

array([1])

In [104]:
a=np.array(y_test)
print(a)
count=0
len(predictions)

[1 1 1 ... 1 1 0]


1

In [105]:
for i in range (len(a)):
    if predictions[0]==a[i]:
        count=count+1

In [106]:
count


947

In [107]:
len(a)


1115

In [108]:
acc= count/len(a)

In [109]:
acc


0.8493273542600897